// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvpengziptdzmjfsdxnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cGVuZ3ppcHRkem1qZnNkeG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTA3NzYsImV4cCI6MjA3MDIyNjc3Nn0.iW_zUE043bXIY4aK8VskNLGJTaGDKBVGfVwPbEgv1c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});